version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      # - python/load-cache
      # - python/install-deps
      # - python/save-cache
      # - run:
      #     command: python -m pytest
      #     name: Test

workflows:
  main:
    jobs:
      - test
