version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.13
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout

      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.13/site-packages
      - restore_cache:
          key: packages1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install --dev --ignore-pipfile
      - save_cache:
          key: packages1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.13/site-packages"

      - run:
          command: |
            pipenv run python -m pytest

workflows:
  main:
    jobs:
      - test
