version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.13
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          command: |
            pip install pipenv
            pipenv install --dev --ignore-pipfile
      - run:
          command: |
            pipenv run python -m pytest

workflows:
  main:
    jobs:
      - test
